Refactor acceptance tests
jan-molak/jenkins-build-monitor-plugin pull request #495
Opened 2021-11-18 20:18 UTC by dcendents

I know we wanted to run the acceptance tests on the oldest supported version as well as the latest. 

I think to be able to test functionalities where badges that used to be in the GroovyPostBuild plugin and in recent jenkins was moved to the badges plugin.

So in maven we have a module with the tests, a second module which runs the same tests but with a different value for `jenkins.version`. The parent project simply aggregates the serenity report. In eclipe we can only run the tests in the `base` project and not in `latest`.

I've refactor the tests to be parameterized instead and can now run against many jenkins versions, it is a single project now so it is easy to run the tests in eclipse as well.

2021-11-18 21:02 UTC, basil commented
This looks great! BTW @dcendents it would be great if we could bump the minimum required Jenkins version to 2.289 or later and merge #472. That would allow the Jenkins core developers to remove a deprecated API that is only being used by this plugin.

2021-11-19 02:42 UTC, dcendents commented
@basil to be fair I've been running a modified version of the build-monitor at work for many years and now I'm trying to fix the tests on master so I can rebase on it and make sure it all works. So to keep it simple I prefer this PR stays as is and only fix the acceptance tests and not modify any production code.

But I've rebased my PR #372 on this one and at the same time I bumped the version to 2.289.1 and replace all occurences of com.google.common.base.Predicate with the java 8 equivalent.

If that one can be merged I think we would both appreciate it.

2021-11-19 08:53 UTC, jan-molak commented
Looks great, thanks @dcendents! I have just one minor suggestion, which I added to the review

2021-11-19 08:53 UTC, jan-molak requested changes

2021-11-19 08:53 UTC, jan-molak commented on build-monitor-acceptance/src/test/java/features/BuildMonitorAbstractBase.java
> +public abstract class BuildMonitorAbstractBase {
I wonder if we could come up with a name other than `AbstractBase` that describes the purpose of this class a bit better. Maybe `BuilMonitorAcceptanceTest`?

2021-11-19 21:33 UTC, merged

2021-11-19 21:34 UTC, jan-molak commented
Merged, thanks! BTW: thank you for all your help, @dcendents and @basil, I really appreciate it :bow: